### PR TITLE
Social Media - Milestone 3 - Frienship V2

### PR DESCRIPTION
**Pull request by arthurborgesdev**
## In this branch me and my partner implemented the following:
* #### Changes in routes to comply with RESTful guidelines
* #### Timeline showing only selected posts, from the friends of the current user
* #### The avoid duplication was implemented using inner functions, not allowing a user to invite a friend which already sent to him or her an invitation.

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:wrench::hammer::full_moon:
**Hi team!
Great job so far:clap::clap:.**

**Major highlights**

- The codebase is clean, easy to read and understand.

However, we still need to make a few changes to get the project approved:muscle:.

**To improve**

- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created
```ruby
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
Kindly implement :point_up: method in the friendship model.

- [x] thanks to this, we can find user friends only by user_id in friendships table
```ruby
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
Kindly implement :point_up: in the `user model`

- [x] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```ruby
# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
Kindly also implement :point_up: feature.

- [x] In order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables)
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
Also implement :point_up:  in the `user model`

- [x] Three tests are currently failing on rspec. See [screen-shot](https://imgur.com/a/lV7FtgQ) for reference. kindly fix this.

**Optional**

- [x] It will be nice to move the logic in application.html.erb under layout in view to a helper. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. check this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) if you need a refresher on how to use a helper in rails.
- [x] Kindly cultivate the habit of committing often. We currently have just one commit for this PR.

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Comment by jmontanholi** [comment]
Hello Eric! By implementing these lines of code we would have duplicated friendships inside of the Friendships database. This is supposed to be avoided right?

```ruby
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
```

**Comment by enaburekhan** [comment]
Sorry for the late reply. We are trying to achieve this `when friendship is confirmed, an additional row with reversed user-friend pair is created` using the method. Maybe you can show me the previous method you implemented. If both are doing exactly the same thing. Which I don't think so. So I will encourage you to implement this base on microverse recommendation.

**Comment by enaburekhan** [comment]
This milestone is mostly about refactoring the existing model and database to improve performance. And not really to duplicate existing functions

**Comment by jmontanholi** [comment]
My point here is that this will duplicate the items in the database only so we can get everyone by user_id, for me it does not make any sense.

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Status: Changes required 👈👈

**I would like you to refer back to the previous code reviewer requested changes**
I followed the discussion you had in the comment section of this PR, my advice for you is that you should follow all the guidelines given. The issue is not about creating a duplicate column in a table, but it's an ID of friendship, we are trying to avoid a situation where an existing friend can send a request back using means other than the UI.

In case you have a question, please reach me on slack as Elisha kyakopo. 

Happing coding🎉✔

**Comment by jmontanholi** [comment]
Hello Elisha! We did the changes the last code reviewer requested. Please take a look at it.

**Comment by elisha2kyakpo1** [comment]
Hey @jmontanholi, How come I can't see them, I have your project open on my PC right now

**Comment by jmontanholi** [comment]
The first one he requested is this one right:

```ruby
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
```

we implemented this but this way

```ruby
def accept_friendship
    @friendship = current_user.inverse_friendships.find(params[:id])
    @friendship.status = 'Accepted'
    @friendship.save
    @friend = User.find(params[:user_id])
    @new_friendship = current_user.friendships.new(status: 'Accepted', friend_id: @friend.id)
    @new_friendship.save
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Friend request accepted' }
    end
  end
```

**Comment by jmontanholi** [comment]
These two can be seen in the user model
```ruby
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

```ruby
# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

**Comment by jmontanholi** [comment]
And this one is in the posts controller.
```Ruby
def friends_and_own_posts
    Post.where(user: (current_user.friends.to_a << current_user))
  end
```

**Comment by elisha2kyakpo1** [comment]
Please submit another request, I have just pulled it, and I can't see any method in the user model, It could be my system. Another reviewer will correct the mistake

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:wrench::hammer::full_moon:
**Hi team!
Great job so far:clap::clap:. We are almost there. However, we still need to make a few changes to get the project approved:muscle:.**

**Mandatory requirements**

- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created
```ruby
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
Move this method to the `friendship model` if you implemented it outside the model. 

- [x] In order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables)

```ruby
def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
Move this method to the `user model` if you implemented it outside the model

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Review by emmanuellekamwa — APPROVED** [review]
Hello team. Congrats on making all the necessary changes 👏🏽👏🏽. Your project now looks great and you can now proceed to the next milestone 🚀🚀.
HAPPY CODING 👨🏽‍💻👨🏽‍💻

**Pull request merged**
